# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'hoozin2' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for hoozin2
  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.9.0'
  pod 'Firebase/Auth', '~> 5.9.0'
  pod 'Firebase/Messaging', '~> 5.9.0'
  pod 'Fabric', '~> 1.7.11'
  pod 'Crashlytics', '~> 3.10.7'
  pod 'Firebase/Database', '~> 5.9.0'
  pod 'Firebase/Storage', '~> 5.9.0'

  target 'hoozin2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
